os: linux

dist: xenial

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      
  - "3.7"
  - "3.8"

install:
  - pip install numpy cython

script:
  - python3 --version
  - g++ --version
  - cmake --version
  - sudo apt-get install -y libeigen3-dev
  - cd requirements && bash clone.bash && bash build.bash && cd ..

  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

  - python setup.py build_ext --inplace && python3 -m unittest discover .
