os: linux
dist: xenial
language: python
script:
  - python3 --version
  - g++ --version
  - cmake --version
  - sudo apt-get install -y libeigen3-dev
  - cd requirements && bash clone.bash && bash build.bash && cd ..

  - python3 -m pip install numpy cython

  - python3 setup.py build_ext --inplace && python3 -m unittest discover .