os: linux
dist: xenial
language: cpp
script:
  - python3 --version
  - g++ --version
  - cmake --version
  # - sudo apt-get install -y libeigen3-dev
  # - cd requirements && bash clone.bash && bash build.bash && cd ..

  - python3 -m pip install cython